name: Database Ping System

on:
  schedule:
    - cron: '*/10 * * * *'  # Every 10 minutes (more reliable)
  workflow_dispatch:
  push:  # Add this for immediate testing
    branches: [ main ]

jobs:
  ping-database:
    runs-on: ubuntu-latest
    
    steps:
      - name: Debug Info
        run: |
          echo "Workflow triggered at: $(date)"
          echo "Trigger event: ${{ github.event_name }}"
          echo "BASE_URL: ${{ secrets.BASE_URL }}"
          
      - name: Ping Database
        run: |
          response=$(curl -s -L -w "\n%{http_code}" "${{ secrets.BASE_URL }}/api/ping")
          http_code=$(echo "$response" | tail -n1)
          body=$(echo "$response" | head -n -1)
          
          echo "Status: $http_code"
          echo "Response: $body"
          
          if [ "$http_code" -eq 200 ]; then
            echo "✅ Success!"
          else
            echo "❌ Failed!"
            exit 1
          fi