name: Database Ping System

on:
  schedule:
    - cron: '0 */12 * * *'  # Every 12 hours
    - cron: '30 6 * * *'    # Daily at 6:30 AM UTC (additional ping)
  workflow_dispatch:

jobs:
  ping-database:
    runs-on: ubuntu-latest
    
    steps:
      - name: Debug Environment
        run: |
          echo "BASE_URL is set to: ${{ secrets.BASE_URL }}"
          echo "Full ping URL will be: ${{ secrets.BASE_URL }}/api/ping"
          echo "Current UTC time: $(date -u)"
          
      - name: Ping Database Multiple Times
        run: |
          echo "Pinging database at: ${{ secrets.BASE_URL }}/api/ping"
          
          # Ping multiple times to ensure database stays active
          for i in {1..3}; do
            echo "Ping attempt #$i"
            
            response=$(curl -s -L -w "\n%{http_code}" "${{ secrets.BASE_URL }}/api/ping")
            http_code=$(echo "$response" | tail -n1)
            body=$(echo "$response" | head -n -1)
            
            echo "HTTP Status: $http_code"
            echo "Response: $body"
            
            if [ "$http_code" -eq 200 ]; then
              echo "✅ Database ping #$i successful!"
            else
              echo "❌ Database ping #$i failed with status: $http_code"
            fi
            
            # Wait 5 seconds between pings
            if [ $i -lt 3 ]; then
              sleep 5
            fi
          done
          
          # Final check - ensure at least one ping was successful
          final_response=$(curl -s -L -w "\n%{http_code}" "${{ secrets.BASE_URL }}/api/ping")
          final_http_code=$(echo "$final_response" | tail -n1)
          
          if [ "$final_http_code" -ne 200 ]; then
            echo "❌ All ping attempts failed"
            exit 1
          fi
          
          echo "✅ Ping system completed successfully"